# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gui_New(object):
    cpath = ""
    def setupUi(self, Gui_New):
        Gui_New.setObjectName("Gui_New")
        Gui_New.resize(1912, 934)
        self.centralwidget = QtWidgets.QWidget(Gui_New)
        self.centralwidget.setObjectName("centralwidget")
        self.GIF_1 = QtWidgets.QLabel(self.centralwidget)
        self.GIF_1.setGeometry(QtCore.QRect(-20, -60, 1931, 1071))
        self.GIF_1.setText("")
        self.GIF_1.setPixmap(QtGui.QPixmap("Jarvis_Gui (2).gif"))
        self.GIF_1.setScaledContents(True)
        self.GIF_1.setObjectName("GIF_1")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(1080, 500, 231, 101))
        self.pushButton_start.setStyleSheet("background-color: rgb(80, 148, 200);\n"
"font: 75 48pt \"MS Shell Dlg 2\";\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(1320, 500, 231, 101))
        self.pushButton_close.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 75 48pt \"MS Shell Dlg 2\";\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.pushButton_close.setObjectName("pushButton_close")
        Gui_New.setCentralWidget(self.centralwidget)

        self.retranslateUi(Gui_New)
        QtCore.QMetaObject.connectSlotsByName(Gui_New)

    def retranslateUi(self, Gui_New):
        _translate = QtCore.QCoreApplication.translate
        Gui_New.setWindowTitle(_translate("Gui_New", "MainWindow"))
        self.pushButton_start.setText(_translate("Gui_New", "START"))
        self.pushButton_close.setText(_translate("Gui_New", "STOP"))

    def __init__(self,path) :
        self.cpath = path   


if __name__ == "__main__":
    import sys
    import os 

    current_path = os.getcwd()
    app = QtWidgets.QApplication(sys.argv)
    Gui_New = QtWidgets.QMainWindow()
    ui = Ui_Gui_New(path=current_path)
    ui.setupUi(Gui_New)
    Gui_New.show()
    sys.exit(app.exec_())
